const Data = {
  products: [
    {
      name: "Free Shirt",
      slug: "Free-shirt",
      category: "Shirts",
      images: "/images/1.webp",
      brand: "Nike",
      rating: "4.5",
      numReviews: "8",
      countInStock: "20",
      description: "A popular shirt",
    },
    {
      name: "Fit-Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      images: "/images/2.webp",
      brand: "Adidas",
      rating: "3.2",
      numReviews: "10",
      countInStock: "20",
      description: "A popular shirt",
    },
    {
      name: "Slim-Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      images: "/images/3.webp",
      brand: "Raymond",
      rating: "4.5",
      numReviews: "3",
      countInStock: "20",
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pantss",
      images: "/images/4.webp",
      brand: "Oliver",
      rating: "2.9",
      numReviews: "13",
      countInStock: "20",
      description: "Smart looking pants",
    },
    {
      name: "T-Shirt",
      slug: "T-shirt",
      category: "T-Shirts",
      images: "/images/5.jpg",
      brand: "Funkey",
      rating: "5",
      numReviews: "12",
      countInStock: "20",
      description: "Over Size T-Shirts",
    },
    {
      name: "Track Pants",
      slug: "Track Pants",
      category: "Pants",
      images: "/images/6.webp",
      brand: "Puma",
      rating: "4",
      numReviews: "34",
      countInStock: "23",
      description: "Track Pants",
    },
    {
      name: "Running Jogger",
      slug: "Running-Jogger",
      category: "Jogger",
      images: "/images/7.webp",
      brand: "Reebok",
      rating: "3.9",
      numReviews: "15",
      countInStock: "54",
      description: "Vitals Solid Running Joggers",
    },
    {
      name: "Jacket",
      slug: "winter Jacket",
      category: "Jacket",
      images: "/images/8.webp",
      brand: "Disel",
      rating: "3.1",
      numReviews: "35",
      countInStock: "13",
      description: "Nice Winter Jacket",
    },
    {
      name: "Boxer Shorts",
      slug: "Boxer",
      category: "Shorts",
      images: "/images/9.webp",
      brand: "Jockey",
      rating: "5",
      numReviews: "57",
      countInStock: "20",
      description: "Cool Jockey Boxer Shorts",
    },
  ],
};

export default Data;
